package Vista;

import Controlador.ControladorPrincipal;
import Controlador.Inicio;
import Modelo.Personaje;
import Modelo.Tuberia;

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos Mario
 */
public class Mapa extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    private ControladorPrincipal controlador;
    
    public Mapa(){
        initComponents();
        this.setSize(1365, 665);
        this.setLocationRelativeTo(null);
    }
    
    public void setControlador(ControladorPrincipal controlador) {
        this.controlador = controlador;
    }
    
    public void AgregaLeucosito(Personaje leucosito)
    {
        this.add(leucosito.getCuerpo());
    }
    
    public void AgregarTuberia(Tuberia tuberia)
    {
        this.add(tuberia.getPared());
    }
    public void AgregaPared(JLabel pared)
    {
        this.add(pared);
        this.repaint();
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        /**
         * Se llama al controlador para que haga el movimiento del Personaje
         * luego se agrega a la pantalla y se vuelve a repintar
         */
        this.controlador.mover(evt);
        if(ControladorPrincipal.FinJuego.equals(true))
        {
            this.dispose();
            Inicio inicio = new Inicio();
            inicio.iniciar("Mundo2");
        }
        else
            this.repaint();
        
    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //this.controlador.moverConBloque(evt);
        this.add(this.controlador.getPersonaje().getCuerpo());
        this.controlador.pintar();
        this.repaint(); 
    }//GEN-LAST:event_formKeyPressed

    public void movimientoBloque(int  movimiento) 
    {
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
